data_dir: './data_train'
chara_nums: 6625
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
lr: 0.00001
batch_size: 16
log_interval: 250
save_interval: 20000
train_step: 200000
sty_encoder_path: './pretrained_models/chinese_styenc.ckpt'
model_save_dir: './finetuned_models'
stroke_path: './chinese_stroke.txt'
classifier_free: True
total_train_step: 400000
resume_checkpoint: './trained_models/model200000.pt'
