data_dir: './data_train'
chara_nums: 6625
diffusion_steps: 1000
noise_schedule: 'linear'
image_size: 80
lr: 0.0001
batch_size: 16
log_interval: 250
save_interval: 20000
train_step: 200000 # conditional training step
sty_encoder_path: './pretrained_models/chinese_styenc.ckpt'
model_save_dir: './trained_models'
stroke_path: './chinese_stroke.txt'
classifier_free: False
total_train_step: 400000 # conditional training + fine-tuning step
resume_checkpoint: ""
